<script setup lang="ts">
import { ref, watch } from "vue";
import type { PropType } from "vue";
import type { AdminSettings, MediaItem } from "@/admin/types";
import { router, useForm, usePage } from "@inertiajs/vue3";
import { usePageHeader } from "@/admin/composables/usePageHeader";
import {
    NTabs,
    NCard,
    NInput,
    NTextarea,
    NSelectWithSearch,
    NSwitch,
    NButton,
    NIcon,
    NFormField,
    NActionBar,
} from "nergous-ui-vue";
import MediaPicker from "@/admin/components/MediaPicker.vue";
import { useUnsavedGuard } from "@/admin/composables/useUnsavedGuard";

const props = defineProps({
    settings: { type: Object as PropType<AdminSettings>, required: true },
});

const form = useForm<{ settings: AdminSettings }>({ settings: props.settings });
useUnsavedGuard(() => form.isDirty);

const tabs = [
    { value: "general", label: "Общие" },
    { value: "seo", label: "SEO" },
    { value: "security", label: "Безопасность" },
];

// The open tab lives in the address (?tab=seo): a link or a reload opens the
// same tab. The address is replaced on the client, without a request; the
// form keeps its unsaved values.
const page = usePage();
const DEFAULT_TAB = "general";
function tabFromUrl(): string {
    const value = new URL(page.url, window.location.origin).searchParams.get(
        "tab",
    );
    return value && tabs.some((t) => t.value === value) ? value : DEFAULT_TAB;
}
const tab = ref(tabFromUrl());
watch(tab, (value) => {
    const url = new URL(page.url, window.location.origin);
    if (value === DEFAULT_TAB) url.searchParams.delete("tab");
    else url.searchParams.set("tab", value);
    const next = url.pathname + url.search;
    if (next !== page.url) {
        router.replace({
            url: next,
            preserveState: true,
            preserveScroll: true,
        });
    }
});

// Match the panel label to the tab ID generated by NTabs.
const panelProps = (value: string) => ({
    id: `settings-panel-${value}`,
    role: "tabpanel",
    "aria-labelledby": `settings-${value}`,
});

// Every IANA zone the browser knows; the server validates with timezone:all.
function zoneList(): string[] {
    const intl = Intl as typeof Intl & {
        supportedValuesOf?: (key: "timeZone") => string[];
    };
    const zones = intl.supportedValuesOf?.("timeZone") ?? [
        "Europe/Moscow",
        "Europe/Kaliningrad",
        "Europe/Samara",
        "Asia/Yekaterinburg",
        "Asia/Novosibirsk",
        "Asia/Krasnoyarsk",
        "Asia/Irkutsk",
        "Asia/Yakutsk",
        "Asia/Vladivostok",
        "Asia/Magadan",
        "Asia/Kamchatka",
    ];
    const set = new Set(["UTC", ...zones]);
    const current = form.settings.general.timezone;
    if (current) set.add(current);
    return [...set];
}
function offsetLabel(zone: string): string {
    try {
        const part = new Intl.DateTimeFormat("en-US", {
            timeZone: zone,
            timeZoneName: "shortOffset",
        })
            .formatToParts(new Date())
            .find((p) => p.type === "timeZoneName");
        return part ? part.value.replace("GMT", "UTC") : "";
    } catch {
        return "";
    }
}
const timezoneOptions = zoneList().map((zone) => ({
    value: zone,
    label: zone === "UTC" ? "UTC" : `${zone} (${offsetLabel(zone)})`,
}));

// Validation errors of a hidden tab are invisible; open the first tab with one.
function tabWithError(errors: Record<string, string>): string | null {
    for (const t of tabs) {
        if (
            Object.keys(errors).some((k) =>
                k.startsWith(`settings.${t.value}.`),
            )
        )
            return t.value;
    }
    return null;
}

function save() {
    form.put("/admin/settings", {
        preserveScroll: true,
        onError: (errors) => {
            const target = tabWithError(errors);
            if (target && target !== tab.value) tab.value = target;
        },
    });
}

function cancel() {
    form.reset();
    form.clearErrors();
}

const pickerOpen = ref(false);
// Image settings chosen from the media library.
type ImageSetting = "favicon" | "og_image";
// Remember which image setting opened the picker.
const pickerTarget = ref<{ setting: ImageSetting; title: string }>({
    setting: "og_image",
    title: "Выбор OG-изображения",
});

function openPicker(setting: ImageSetting, title: string) {
    pickerTarget.value = { setting, title };
    pickerOpen.value = true;
}
function setImage(setting: ImageSetting, url: string) {
    if (setting === "favicon") form.settings.general.favicon = url;
    else form.settings.seo.og_image = url;
}
function selectImage(items: MediaItem[]) {
    const img = items[0];
    if (!img) return;
    setImage(pickerTarget.value.setting, img.url);
}
function clearImage(setting: ImageSetting) {
    setImage(setting, "");
}

usePageHeader(() => ({
    title: "Настройки",
    subtitle: "Конфигурация и SEO",
}));
</script>

<template>
    <div class="settings">
        <NTabs
            v-model="tab"
            :tabs="tabs"
            id-base="settings"
            class="settings__tabs"
            aria-label="Разделы настроек"
        />

        <NCard v-show="tab === 'general'" v-bind="panelProps('general')">
            <header class="card-head">
                <span class="card-head__icon">
                    <NIcon name="settings" :size="20" />
                </span>
                <div class="card-head__text">
                    <h2 class="card-head__title">Основные</h2>
                    <div class="card-head__sub">
                        Название приложения и часовой пояс
                    </div>
                </div>
            </header>

            <div class="card-body">
                <NFormField
                    label="Название приложения"
                    :error="form.errors['settings.general.app_name']"
                >
                    <NInput
                        v-model="form.settings.general.app_name"
                        placeholder="app-name"
                    />
                </NFormField>

                <NFormField
                    label="Часовой пояс"
                    hint="Даты в админке показываются в этом поясе; в базе они хранятся в UTC"
                    :error="form.errors['settings.general.timezone']"
                    tag="div"
                >
                    <NSelectWithSearch
                        v-model="form.settings.general.timezone"
                        :options="timezoneOptions"
                        search-placeholder="Найти часовой пояс…"
                        :error="!!form.errors['settings.general.timezone']"
                    />
                </NFormField>

                <NFormField
                    label="Favicon"
                    hint="Иконка вкладки браузера — выбирается из медиатеки"
                    tag="div"
                >
                    <div class="og-picker">
                        <div
                            v-if="form.settings.general.favicon"
                            class="og-picker__preview og-picker__preview--fav"
                        >
                            <img
                                :src="form.settings.general.favicon"
                                alt="Favicon"
                            />
                        </div>
                        <div
                            v-else
                            class="og-picker__empty og-picker__empty--fav"
                        >
                            <NIcon name="asset" :size="18" />
                        </div>
                        <div class="og-picker__actions">
                            <NButton
                                variant="secondary"
                                type="button"
                                @click="openPicker('favicon', 'Выбор favicon')"
                            >
                                {{
                                    form.settings.general.favicon
                                        ? "Изменить"
                                        : "Выбрать"
                                }}
                            </NButton>
                            <NButton
                                v-if="form.settings.general.favicon"
                                variant="ghost"
                                tone="danger"
                                type="button"
                                @click="clearImage('favicon')"
                            >
                                Убрать
                            </NButton>
                        </div>
                    </div>
                </NFormField>
            </div>
        </NCard>

        <NCard v-show="tab === 'seo'" v-bind="panelProps('seo')">
            <header class="card-head">
                <span class="card-head__icon">
                    <NIcon name="globe" :size="20" />
                </span>
                <div class="card-head__text">
                    <h2 class="card-head__title">SEO и индексация</h2>
                    <div class="card-head__sub">
                        Мета-теги, карта сайта, доступ роботов
                    </div>
                </div>
            </header>

            <div class="card-body">
                <NFormField
                    label="Шаблон meta-заголовка"
                    hint="%s заменяется названием страницы"
                    :error="form.errors['settings.seo.meta_title_template']"
                >
                    <NInput
                        v-model="form.settings.seo.meta_title_template"
                        placeholder="%s — app-name"
                    />
                </NFormField>

                <NFormField
                    label="Meta-описание"
                    :error="form.errors['settings.seo.meta_description']"
                >
                    <NTextarea
                        v-model="form.settings.seo.meta_description"
                        :rows="3"
                        placeholder="Краткое описание сайта для поисковой выдачи"
                    />
                </NFormField>

                <NFormField
                    label="Канонический домен"
                    :error="form.errors['settings.seo.canonical_domain']"
                >
                    <NInput
                        v-model="form.settings.seo.canonical_domain"
                        placeholder="https://example.com"
                    />
                </NFormField>

                <NFormField
                    label="OG-изображение"
                    hint="Превью ссылки в соцсетях — выбирается из медиатеки"
                    tag="div"
                >
                    <div class="og-picker">
                        <div
                            v-if="form.settings.seo.og_image"
                            class="og-picker__preview"
                        >
                            <img
                                :src="form.settings.seo.og_image"
                                alt="OG-изображение"
                            />
                        </div>
                        <div v-else class="og-picker__empty">
                            <NIcon name="asset" :size="22" />
                            <span>Изображение не выбрано</span>
                        </div>
                        <div class="og-picker__actions">
                            <NButton
                                variant="secondary"
                                type="button"
                                @click="
                                    openPicker(
                                        'og_image',
                                        'Выбор OG-изображения',
                                    )
                                "
                            >
                                {{
                                    form.settings.seo.og_image
                                        ? "Изменить"
                                        : "Выбрать"
                                }}
                            </NButton>
                            <NButton
                                v-if="form.settings.seo.og_image"
                                variant="ghost"
                                tone="danger"
                                type="button"
                                @click="clearImage('og_image')"
                            >
                                Убрать
                            </NButton>
                        </div>
                    </div>
                </NFormField>

                <div class="toggle-list">
                    <label class="toggle-row">
                        <div class="toggle-row__text">
                            <b>Индексация поисковиками</b>
                            <span>robots: index / noindex</span>
                        </div>
                        <NSwitch
                            v-model="form.settings.seo.indexable"
                            aria-label="Индексация поисковиками"
                        />
                    </label>

                    <label class="toggle-row">
                        <div class="toggle-row__text">
                            <b>Карта сайта (sitemap.xml)</b>
                            <span
                                >Флаг для публичной части: генерацию подключает
                                разработчик сайта</span
                            >
                        </div>
                        <NSwitch
                            v-model="form.settings.seo.sitemap"
                            aria-label="Карта сайта (sitemap.xml)"
                        />
                    </label>
                </div>
            </div>
        </NCard>

        <NCard v-show="tab === 'security'" v-bind="panelProps('security')">
            <header class="card-head">
                <span class="card-head__icon">
                    <NIcon name="lock" :size="20" />
                </span>
                <div class="card-head__text">
                    <h2 class="card-head__title">Безопасность</h2>
                    <div class="card-head__sub">
                        Время жизни сессии и лимит попыток входа
                    </div>
                </div>
            </header>

            <div class="card-body">
                <div class="grid-2">
                    <NFormField
                        label="Время жизни сессии, мин"
                        :error="
                            form.errors['settings.security.session_lifetime']
                        "
                    >
                        <NInput
                            v-model="form.settings.security.session_lifetime"
                            type="number"
                            min="1"
                            max="43200"
                            placeholder="120"
                        />
                    </NFormField>

                    <NFormField
                        label="Лимит попыток входа"
                        hint="В минуту с одного адреса и email"
                        :error="form.errors['settings.security.login_throttle']"
                    >
                        <NInput
                            v-model="form.settings.security.login_throttle"
                            type="number"
                            min="1"
                            max="1000"
                            placeholder="5"
                        />
                    </NFormField>
                </div>
            </div>
        </NCard>
        <NActionBar :dirty="form.isDirty">
            <NButton
                variant="secondary"
                :disabled="!form.isDirty || form.processing"
                @click="cancel"
            >
                Отменить изменения
            </NButton>
            <NButton
                variant="primary"
                icon="check"
                :loading="form.processing"
                :disabled="!form.isDirty"
                data-enter-submit
                @click="save"
            >
                Сохранить
            </NButton>
        </NActionBar>
    </div>

    <MediaPicker
        v-model="pickerOpen"
        type="image"
        :max="1"
        :title="pickerTarget.title"
        confirm-label="Выбрать"
        @select="selectImage"
    />
</template>

<style scoped>
.settings {
    display: flex;
    flex-direction: column;
    gap: 22px;
    max-width: 940px;
    /* leave room so the floating bar never covers the last fields */
    padding-bottom: 96px;
}
.settings__tabs {
    margin-bottom: 2px;
}
.card-head {
    display: flex;
    align-items: center;
    gap: 13px;
    margin-bottom: 22px;
}
.card-head__icon {
    width: 40px;
    height: 40px;
    border-radius: 11px;
    background: var(--accent-soft);
    color: var(--accent);
    display: flex;
    align-items: center;
    justify-content: center;
    flex: none;
}
.card-head__title {
    margin: 0;
    font-size: 16px;
    font-weight: 800;
    letter-spacing: -0.01em;
    color: var(--text);
}
.card-head__sub {
    font-size: 12.5px;
    color: var(--text-3);
    margin-top: 2px;
}

.card-body {
    display: flex;
    flex-direction: column;
    gap: 18px;
}
.grid-2 {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
}

.toggle-list {
    display: flex;
    flex-direction: column;
    gap: 2px;
}
.toggle-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    padding: 14px 0;
    border-top: 1px solid var(--border);
    /* whole row is a <label> — clicking the caption toggles the switch */
    cursor: pointer;
}
.toggle-row:first-child {
    border-top: none;
}
.toggle-row__text b {
    display: block;
    font-size: 13.5px;
    font-weight: 700;
    color: var(--text);
}
.toggle-row__text span {
    display: block;
    font-size: 12px;
    color: var(--text-3);
    margin-top: 2px;
}

.og-picker {
    display: flex;
    align-items: center;
    gap: 14px;
}
.og-picker__preview {
    width: 120px;
    height: 75px; /* ~16/10 */
    border-radius: var(--radius-md);
    overflow: hidden;
    border: 1px solid var(--border);
    background: var(--surface-3);
    flex: none;
}
.og-picker__preview img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
}
.og-picker__empty {
    width: 120px;
    height: 75px;
    border-radius: var(--radius-md);
    border: 1px dashed var(--border-2);
    background: var(--surface-2);
    color: var(--text-3);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 4px;
    font-size: 11.5px;
    text-align: center;
    flex: none;
}
.og-picker__preview--fav,
.og-picker__empty--fav {
    width: 64px;
    height: 64px;
}
.og-picker__actions {
    display: flex;
    gap: 8px;
}

@media (max-width: 720px) {
    .grid-2 {
        grid-template-columns: 1fr;
    }
}
</style>
